name: CSS Syntax Checking

on:
  push:
    branches:
    - main
    - WaveFox-Nightly
  pull_request:
    branches: 
    - main
    - WaveFox-Nightly

jobs:
  Lint_CSS:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repository
      uses: actions/checkout@v4

    - name: Run Stylelint
      run: |
        npm install stylelint stylelint-config-standard
        echo '{"extends": "stylelint-config-standard"}' > .stylelintrc.json
        npx stylelint "**/*.css" --formatter string
