name: CSS Syntax Checking

on:
  push:
    branches:
    - main
    - WaveFox-Nightly
  pull_request:
    branches: 
    - main
    - WaveFox-Nightly

jobs:
  Lint_CSS:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run Stylelint
      run: npx stylelint "**/*.css" --formatter github
